### PR TITLE
Migrate to JSDomNodeJSEnv

### PR DESCRIPTION
**Pull request by xerial**
This is a follow-up PR of this chat: https://gitter.im/monadic-html/Lobby?at=5a30be9887680e623005f7ec

- [x] Use Node.js for testing because PhantomJS support in Scala.js is deprecated
- [x] Fix test failures

### CODE REVIEW

**Comment by xerial** [comment]
An error in my local machine:
```
[info] - README examples *** FAILED *** (38 milliseconds)
[info]   "...div><div></div><imgs[tyle="width:100px;"src="http://doge2048.com/meta/doge-600.png]"></div>" did not equal "...div><div></div><imgs[rc="http://doge2048.com/meta/doge-600.png"style="width:100px;]"></div>" (HtmlTests.scala:262)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at $c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:22587:14)
[info]   at $c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_Throwable.init___T__jl_Throwable(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:22609:8)
[info]   at $c_Lorg_scalatest_exceptions_TestFailedException.$c_jl_RuntimeException.init___jl_Throwable(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:32863:52)
[info]   at $c_Lorg_scalatest_exceptions_TestFailedException.$c_Lorg_scalatest_exceptions_StackDepthException.init___F1__s_Option__s_util_Either(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:40930:56)
[info]   at org.scalatest.exceptions.TestFailedException.<init>(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:53992:97)
[info]   at org.scalatest.exceptions.TestFailedException.<init>(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:53972:107)
[info]   at org.scalatest.Assertions.newAssertionFailedException(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:20004:65)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:5967:60)
[info]   at {anonymous}()(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:57887:36)
[info]   at scala.scalajs.runtime.AnonFunction0.apply(/Users/leo/work/git/monadic-html/monadic-html/target/scala-2.12/monadic-html-test-fastopt.js:30598:23)
```

**Comment by xerial** [comment]
Rebased on the master branch

**Comment by xerial** [comment]
@OlivierBlanvillain This test failure was a simple fix and found to be a different issue I experienced. But anyway, this change will be necessary now that phantomjs support is deprecated.

I might create another PR if I can reproduce the issue.

Thanks.

**Comment by OlivierBlanvillain** [comment]
Thanks @xerial!

**Pull request merged**
