### PR TITLE
Add srcset as attribute

### PR DESCRIPTION
**Pull request by olafurpg**
See http://w3c.github.io/html/semantics-embedded-content.html#element-attrdef-img-srcset

### CODE REVIEW

**Comment by olafurpg** [comment]
I don't know where to find an up-to-date list of legal attributes, would be nice to solve this once and for all instead of iteratively add one-by-one.

**Comment by olafurpg** [comment]
Realized the list needs to be ordered for binary search to work. It would be nice if it was easier to add custom attributes to DevSettings.

**Comment by OlivierBlanvillain** [comment]
```scala
trait DevSettings2 extends DevSettings {
  override lazy val attributes: Array[String] = ("yolo" :+ super.attributes).sorted
}
```

If we can find a good source for elements / attributes / events the best would be to have a curl + grep script to update these things automatically. Hardest part is probably aligning comas :P

**Comment by OlivierBlanvillain** [comment]
The above does not quite work because of the `lazy val`, but making it a `def` should be enought

**Comment by olafurpg** [comment]
That's what I'm doing, but I only want to use this for dev settings, so I ended up with

```scala
trait DevSettings2 extends DevSettings {
  lazy val superAttrs = new DevSettings{}.attributes
  override lazy val attributes: Array[String] = ("yolo" :+ superAttrs).sorted
}
if (LinkingMode.productionMode) MountSettings.default
else new DevSettings2
```

It should be fairly simple to wrap this into a helper method, something like `MountSetttings.custom(extraAttributes = ..., ...)`

**Pull request closed without merging**
