### PR TITLE
Upgrade to Scala.js 1.x and setup GitHub Actions

### LINKED ISSUE #115: scalajs 1.x support
Scala is already at 1.0.x versions

### PR DESCRIPTION
**Pull request by olafurpg**
Previously, monadic-html only worked with Scala.js v0.6.x. This commit

* upgrades to Scala.js v1.3.0
* upgrades to Scala 2.13.3 and fixes new deprecation warnings
* migrates the CI from Travis to GitHub Actions
* refactors the build to setup automated CI releases

Fixes #115

### CODE REVIEW

**Comment by olafurpg** [comment]
The GitHub Actions CI is not running since the master branch is missing a placeholder workflow. 

In order to use the newly automated CI releases, you will need to add 4 new secrets according to https://github.com/olafurpg/sbt-ci-release/

* PGP_PASSPHRASE
* PGP_SECRET
* SONATYPE_USERNAME
* SONATYPE_PASSWORD

@OlivierBlanvillain I can send you some valid PGP values if you don't mind reusing them from other projects, nobody checks the signatures anyways.

**Comment by simon-morgan** [comment]
@olafurpg thanks for getting this pr done - I've been eagerly watching for the move to Scala.js 1.x.
@OlivierBlanvillain, firstly thanks for a this great Dom binding library - I use it every day! Secondly, is there any help I can provide to get this pr merged and released?

**Comment by OlivierBlanvillain** [comment]
@olafurpg Thank you so much for this PR, it looks great! Sorry for not looking into it earlier, I was under heavy workload in the last few weeks...

I reverted the change to `cancel` since I would like to avoid breaking changes...

I'm going to merge this as is and test the CI in a subsequent PR :rocket:

**Comment by olafurpg** [comment]
@OlivierBlanvillain Thank you for commandeering this PR! There's no rush on my side, I found myself playing with Scala.js and wanted to use monadic-html because I still think it's the nicest library in this space.

The SNAPSHOT release appears to have worked 🎉 https://github.com/OlivierBlanvillain/monadic-html/actions?query=workflow%3ARelease

Have you tried to push a git tag to cut a stable release?

**Comment by OlivierBlanvillain** [comment]
@olafurpg I just tried pushing a tag but the CI didn't like it:
https://github.com/OlivierBlanvillain/monadic-html/runs/1757828865

Any idea?

**Comment by olafurpg** [comment]
I have seen this error before and I recall it was related to a missing `skip in publish := true` for projects that have no source code 🤔

This can happen when the root project is missing `skip in publish := true`, but that doesn't seem to be the case for `build.sbt` in this repo.


The `publishTo` setting is overridden by some plugin. The value is correct when I check locally.
```
# On my local computer
> show publishTo
[info] monadic-rx-catsJS / publishTo
[info] 	Some(FileRepository(sonatype-local-bundle, Patterns(ivyPatterns=Vector(), artifactPatterns=Vector(/Users/olafurpg/dev/OlivierBlanvillain/monadic-html/target/sonatype-staging/0.4.1/[organisation]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[artifact]-[revision](-[classifier]).[ext]), isMavenCompatible=true, descriptorOptional=false, skipConsistencyCheck=false), FileConfiguration(true, None)))
> publish
[info] Wrote /Users/olafurpg/dev/OlivierBlanvillain/monadic-html/monadic-rx/js/target/scala-2.13/monadic-rx_sjs1_2.13-0.4.1.pom
[info] Wrote /Users/olafurpg/dev/OlivierBlanvillain/monadic-html/monadic-rx-cats/.js/target/scala-2.13/monadic-rx-cats_sjs1_2.13-0.4.1.pom
[info] Wrote /Users/olafurpg/dev/OlivierBlanvillain/monadic-html/monadic-html/target/scala-2.13/monadic-html_sjs1_2.13-0.4.1.pom
[info] 	published monadic-rx_sjs1_2.13 to /Users/olafurpg/dev/OlivierBlanvillain/monadic-html/target/sonatype-staging/0.4.1/in/nvilla/monadic-rx_sjs1_2.13/0.4.1/monadic-rx_sjs1_2.13-0.4.1.pom
```

However, the CI logs indicate that `sbt publish` is not going to the Sonatype bundle directory.

```
# CI logs
[info] 	published monadic-rx_sjs1_2.12 to oss.sonatype.org/content/repositories/snapshots/in/nvilla/monadic-rx_sjs1_2.12/0.4.1+0-4eb44c19+20210124-1725-SNAPSHOT/monadic-rx_sjs1_2.12-0.4.1+0-4eb44c19+20210124-1725-SNAPSHOT-sources.jar.asc
```

**Comment by olafurpg** [comment]
I opened https://github.com/OlivierBlanvillain/monadic-html/pull/118 to disable the Sontatype bundle release, but I'm not sure why `sbt publishTo` is not using the `sonatypeBundleDirectory` in CI. It's working as expected for me locally.

**Pull request merged**
